### ISSUE TITLE
Mobile homepage issues

### ISSUE THREAD

**Issue by Cephandrius42** [gryphonmachine/machine#1]
On an iPhone 12 mini, the homepage has text wrapping beyond the size of its box:
![728B4721-466B-4130-B965-C1EFD8D031DE](https://user-images.githubusercontent.com/94200651/235375212-8935484a-8c17-4fb0-94df-42e08eb4f775.jpeg)

In addition, the icons for the GitHub, Discord, and Ko-Fi are all white on white. The search bar also extends past the edge of the page. 
![A260A2D7-88F5-4FAB-90A5-E4BB4B6BCA01](https://user-images.githubusercontent.com/94200651/235375288-a22612f6-7fc8-4c16-a0da-25ede69e3ca9.jpeg)

(This is my first time leaving an issue on an open-source repo, feel free to provide feedback on better naming of issues and other problems with this.)

**Comment by heybereket** [comment]
Hey! Thank you so much for reporting this. The issue was great!

This has all been fixed as of 1ed4599d91924da406b2962f2d2be437062df9d5. Let me know if there are any more issues you encounter!
