### ISSUE TITLE
NaNpts

### ISSUE THREAD

**Issue by Autumn-Ou** [gryphonmachine/machine#12]
**Describe the bug**
NaNpts for the insights tab unless you refresh the page and wait, no Idea what the source of this is, most likely delay for getting data is so long that the page is generated without it.

![image](https://github.com/gryphonmachine/machine/assets/62668093/9cc69b18-5c3d-4c0c-8231-7041b19fd66d)

**Comment by heybereket** [comment]
Should be fixed as of 31847534e8ba06394a77c44cd58f258ac20a8090.
