### ISSUE TITLE
Rendering Search Results Under Other Panels

### ISSUE THREAD

**Issue by Autumn-Ou** [gryphonmachine/machine#14]
**Describe the bug**
Search results menu renders under the content but above the panel of the content below

**To Reproduce**
1. Open a teams page
2. Click on search
3. Start typing

**Screenshots**
![image](https://github.com/gryphonmachine/machine/assets/62668093/74521df2-3c09-454f-8588-ce6a4246a85d)

**Browser**
- OS: Windows 11
- Browser Edge *Chromium Backend*

**Comment by heybereket** [comment]
Fixed as of 20f39bcdbc1d1e79e62326dcd393e1cc307b54f5
