### ISSUE TITLE
Off-season False on off-season events

### ISSUE THREAD

**Issue by Autumn-Ou** [gryphonmachine/machine#21]
**Describe the bug**
Displays small tag labeled off season false on events like Duel down under and battle cry

**To Reproduce**

1. Open events page
2. Select an off season event

**Screenshots**
![image](https://github.com/gryphonmachine/machine/assets/62668093/c9e085a3-6590-4999-a7e7-18bc6e21de00)

**Browser**

- OS: iOS16
- Browser: Chrome

**Additional context**
None

**Comment by eternalmoon1234** [comment]
Resolved as of [747200c](https://github.com/gryphonmachine/machine/commit/747200c75a8b74e89feddd7bb2cef23b86e1d633).
