### ISSUE TITLE
Sign out Random Text

### ISSUE THREAD

**Issue by Autumn-Ou** [gryphonmachine/machine#43]
**Describe the bug**
On sign-out a small textbox displaying all supported platforms pops up, rendering issue should not be shown.

**Steps To Reproduce**
Steps to reproduce the behavior the UI issue:

1. Be signed in
2. Click user icon
3. Select sign-out

**Screenshots**
![image](https://github.com/scoutmachine/web/assets/62668093/d3e58778-e38e-4287-a1c3-cf6c832ae05d)

**Browser**

- OS: Windows 11
- Browser: Edge *Chromium Backend*

**Additional context**
None

**Comment by heybereket** [comment]
Fixed as of 954fc964f73f0ec05976a8a1b550861a228cbe57.
