### ISSUE TITLE
Match order

### ISSUE THREAD

**Issue by Tijn4481** [gryphonmachine/machine#46]
Currently, the order of matches that a team played at a tournament is a bit wonky IMO. For me the logical order would be qualifying match 1 ... quarter-finals match 1 ... semi-final match 1 ... finals match 1 ... or the other way around if it is preferred to go from last to first.
But currently, it looks like this where the quarterfinal matches are noted first, followed by semis and then qualifying matches.
![image](https://github.com/scoutmachine/web/assets/51416698/cd4bbd15-6731-46c7-9f72-7cca483ac7cb)

**Comment by heybereket** [comment]
Hey, thanks for bringing this issue up. What's the event code for this or what team page were you viewing that has this event? Once we have that info, we'll take a closer look. Thanks!

**Comment by Tijn4481** [comment]
Hey I saw it on 4481s page.

**Comment by heybereket** [comment]
Hey @Tijn4481. Super sorry about this again! This should now be fixed as of 8cbe0eb2ef1393fe0987b78bdcde7b26be7acdeb. Let me know if there are any other bugs.
