### ISSUE TITLE
Search Bar Overflow on Desktop & Improper Render in iOS Safari

### ISSUE THREAD

**Issue by Autumn-Ou** [gryphonmachine/machine#5]
**Describe the bug**
On desktop the search bar in narrower browser windows will overflow out of the header box.

**To Reproduce**
1. Open main page.
2. Change to narrow browser window and the bar will overflow off the page, and outside of the header box.

**Screenshots**

Desktop
![image](https://github.com/gryphonmachine/machine/assets/62668093/21359c70-f0dd-4fa8-a66e-b885acf3bf1d)

iOS
![image](https://github.com/gryphonmachine/machine/assets/62668093/e7a08b72-4c3c-4243-8555-92ac6b150138)

**Browser**
- OS: Windows 11,
- Browser: Edge *Chromium backend*

- OS: iOS 16
- Browser Safari & Chrome *Apple Web Kit backend*

**Additional context**
None.

**Solutions**
change header to multilayer if too narrow instead of keeping it single layer, give a dynamic size to the search bar to keep it always constrained.

**Comment by Autumn-Ou** [comment]
![image](https://github.com/gryphonmachine/machine/assets/62668093/1975f36e-98a0-425e-9cfe-8f2d45f471b7)

**Comment by heybereket** [comment]
Fixed improper render on iOS as of b795927c435d41dbd209f3978e20dc7ad06524
<img width="358" alt="Screenshot 2023-05-14 at 1 49 26 PM" src="https://github.com/gryphonmachine/machine/assets/68391329/9797bef2-b760-4b3d-b678-31704b2ef955">

<img width="357" alt="Screenshot 2023-05-14 at 1 49 56 PM" src="https://github.com/gryphonmachine/machine/assets/68391329/658573d6-f1cc-4923-a6b5-746a0dae81db">

**Comment by Autumn-Ou** [comment]
![image](https://github.com/gryphonmachine/machine/assets/62668093/8245b9a5-179f-43c0-b70b-87085ba80175)
![image](https://github.com/gryphonmachine/machine/assets/62668093/0882164a-4614-466e-80d3-5ac0b876b320)
Transition just needs to happen around 200 px earlier

**Comment by heybereket** [comment]
I see - fixed as of 806150a472ed1dce7a73c9a622fa420cd53bf034!
