### ISSUE TITLE
Pit Display Upcomming Match

### ISSUE THREAD

**Issue by Autumn-Ou** [gryphonmachine/machine#50]
**Is your feature request related to a problem? Please describe.**
A display of the upcoming match for a team while at a competition, display robots for both sides, EPA, & match win chance

**Describe the solution you'd like**
Implementation of this page & CD post
https://www.chiefdelphi.com/t/frc-pit-display/437158

![image](https://github.com/scoutmachine/web/assets/62668093/41a075aa-0ee4-4415-b59d-7f38b399d4b3)

**Comment by heybereket** [comment]
Started working on this as of 1d4acee54c72d5e014dd62089b21a1ac452344bf.
