### ISSUE TITLE
Auto merge Dependabot Workflow

### ISSUE THREAD

**Issue by heybereket** [gryphonmachine/machine#53]

**Comment by Autumn-Ou** [comment]
Should be done, just have to wait until next PR from dependabot to confirm

**Comment by heybereket** [comment]
Seems to not have worked. https://github.com/scoutmachine/web/pull/54

**Comment by gautvm** [comment]
Yeah it didn't work again.

**Comment by heybereket** [comment]
Deciding to remove it as of now - seems to not work globally.
