### ISSUE TITLE
Features Panel Links / Interaction

### ISSUE THREAD

**Issue by Autumn-Ou** [gryphonmachine/machine#9]
**Request**
All the features you could ever want... panel on main page have the small tabs link to their part of the site if applicable for example "event pages" & "2023 rookie teams"

**Additional context**
It's just weird to have them and they have an effect on hover implying that they're interactable but on click do nothing when they could clearly act as links.

![image](https://github.com/gryphonmachine/machine/assets/62668093/003e096b-bc43-4554-b079-cb9ac58a0046)

**Comment by eternalmoon1234** [comment]
Good point, I'll add this in.

**Comment by eternalmoon1234** [comment]
Resolved in [f01dd13](https://github.com/gryphonmachine/machine/commit/f01dd13b9c2cda84b811d1acc7ae07a3cbebab3c).
